// flow-typed signature: b84ee67f714f85d2f2ec2cae2d8bbb61
// flow-typed version: <<STUB>>/gatsby-plugin-mailchimp_v5.2.2/flow_v0.133.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-plugin-mailchimp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-plugin-mailchimp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-plugin-mailchimp/__tests__/gatsby-node.test' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mailchimp/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby-plugin-mailchimp/jest.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-plugin-mailchimp/__tests__/gatsby-node.test.js' {
  declare module.exports: $Exports<'gatsby-plugin-mailchimp/__tests__/gatsby-node.test'>;
}
declare module 'gatsby-plugin-mailchimp/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-plugin-mailchimp/gatsby-node'>;
}
declare module 'gatsby-plugin-mailchimp/index' {
  declare module.exports: $Exports<'gatsby-plugin-mailchimp'>;
}
declare module 'gatsby-plugin-mailchimp/index.js' {
  declare module.exports: $Exports<'gatsby-plugin-mailchimp'>;
}
declare module 'gatsby-plugin-mailchimp/jest.config.js' {
  declare module.exports: $Exports<'gatsby-plugin-mailchimp/jest.config'>;
}
